LinkedIn Ads source documentation
AdobeDocs/experience-platform.en pull request #104
Opened 2022-08-16 07:25 UTC by mohan-h

Initial commit

2022-08-25 22:40 UTC, carlojavier requested changes
@mohan-h looking good, some comments added!

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +| `pivot` | One of `ACCOUNT`, `CAMPAIGN GROUP`, `CAMPAIGN` or `CREATIVE` |
Can we add a brief definition or description to what `pivot` is?

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +[[!DNL LinkedIn Ads]](https://business.linkedin.com/marketing-solutions/ads) is a marketing solution by LinkedIn to reach over 830 million professionals on the world's largest professional network. T
- Let's rephrase the first sentence to: "...is a marketing solution by LinkedIn that can reach over 830..."
- And a slight restructuring to the second sentence: "...key insights on performance such as clicks, impressions, and ad spend, as well as demographic information like metrics by demographic values at the account, campaign, and creative levels."

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +This Adobe Experience Platform [source](https://experienceleague.adobe.com/docs/experience-platform/sources/home.html?lang=en) leverages the [LinkedIn Reporting & ROI APIs](https://docs.microsoft.com
- Some restructuring here: "...to retrieve your LinkedIn campaign data, along with all performance and metrics. You can then bring that data to Experience Platform, where you can execute analytics."
- "The data is returned from a specified date with a default of six month retention period for daily data." (Let me know if this rephrasing still works for the meaning.)

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +| Campaign IDs | You can find guidance to obtain the Campaign Group ID [here](https://www.linkedin.com/help/lms/answer/a424270). | `1991010101,1992020202` |
For the API side, can we wrap the credentials in backticks and write them out in camelcase

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +See the Retention, Restrictions, Delays and Accuracy sections on the [LinkedIn Reporting & ROI APIs](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/ads-reporting) page
Let's move the second sentence into an actual note:

>[!NOTE]
>
>LinkedIn Ads only allows data retrieval from active campaigns.The data is returned from a specified date with a default of six month retention period for daily data."

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +To validate that you have correctly set up the source; and [!DNL LinkedIn Ads] events are being ingested, follow the steps below:
Semi-colon (`;`) is unnecessary here

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +![Platform UI screenshot for LinkedIn Ads Preview Dataset](../../../../images/tutorials/create/linkedin-ads/preview-dataset.png?lang=en)
Can the screenshot be updated here? There is a typo on the dataset name "Tset123"

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +[[!DNL LinkedIn Ads]](https://business.linkedin.com/marketing-solutions/ads) is a marketing solution by LinkedIn to reach over 830 million professionals on the world's largest professional network. T
Same as API:
Let's rephrase the first sentence to: "...is a marketing solution by LinkedIn that can reach over 830..."
And a slight restructuring to the second sentence: "...key insights on performance such as clicks, impressions, and ad spend, as well as demographic information like metrics by demographic values at the account, campaign, and creative levels."

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +See the Retention, Restrictions, Delays and Accuracy sections on the [LinkedIn Reporting & ROI APIs](https://docs.microsoft.com/en-us/linkedin/marketing/integrations/ads-reporting/ads-reporting) page
Same comment as API about moving the note into its own [!NOTE] tag

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +
I think we need to preface this particular part about why a user needs to schedule specifically for Day or Hour? Can we add a brief intro here on why this is recommended/required?

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +> Multiple IDs can be specified by passing comma separated values.
Need to remove space between ">" and the text

2022-08-25 22:40 UTC, carlojavier commented on help/sources/tutorials/ui/create/advertising/linkedin-ads.md
> +| campaignIds | Your LinkedIn Campaign IDs. |
let's wrap the entries in the fields column in backticks

2022-08-29 13:45 UTC, mohan-h commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +This Adobe Experience Platform [source](https://experienceleague.adobe.com/docs/experience-platform/sources/home.html?lang=en) leverages the [LinkedIn Reporting & ROI APIs](https://docs.microsoft.com
Used _The data is returned from a specified date within the six month default retention period for daily data._

2022-08-29 13:46 UTC, mohan-h commented on help/sources/tutorials/api/create/advertising/linkedin-ads.md
> +This Adobe Experience Platform [source](https://experienceleague.adobe.com/docs/experience-platform/sources/home.html?lang=en) leverages the [LinkedIn Reporting & ROI APIs](https://docs.microsoft.com
Used _The data is returned from a specified date within the six month default retention period for daily data._

2023-09-18 17:36 UTC, carlojavier commented
Closing due to inactivity. The PR is ready on internal, still just waiting on approval from internal on when it can be published.

2023-09-18 17:36 UTC, closed without merging