Customer.io webhook
AdobeDocs/experience-platform.en pull request #183
Opened 2023-02-17 09:56 UTC by mohan-h

Initial commit

2023-02-22 22:01 UTC, carlojavier requested changes
looking good! thanks for making the source overview page too! pls see comments

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +## Prerequisites - Sample JSON to define source schema for [!DNL Customer.io] {#prerequisites-json-schema}
Let's add a short intro here and move the JSON part into its own H3. So something like:
## Prerequisites 
The following section provides information on prerequisites to complete before you can create a [!DNL Customer.io]  source connection.

### Sample JSON to define the source schema for [!DNL Customer.io]

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +Before creating a [!DNL Customer.io] source connection, you must also ensure that you first create a Platform schema to use for your source. See the tutorial on [creating a Platform schema](../../../
We can remove the "Before creating a [!DNL Customer.io] source connection," here and start with "You must also ensure..."

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +
We can remove this section, just an optional space for where webhook integration can be added to

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +| `timestamp` | Timestamp when the event occurred. |
Good call on the table here! One small suggestion: can we make the descriptions into full sentences? Just add a "The" before each of them.

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +>[!NOTE]
Let's turn this into an important tag:
>[!IMPORTANT]
>
>Do not map...

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +Note down the values of the fields below:
Let's rephrase this to: "You must retrieve the following in order to construct a URL:"

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +Example of a constructed webhook URL: ``https://dcs.adobedc.net/collection/febc116d22ba0ea2868e9c93b199375302afb8a589617700991bb8f3f0341ad7?x-adobe-flow-id=439b3fc4-3042-4a3a-b5e0-a494898d3fb0``
Once you have retrieved your streaming endpoint and dataflow ID, build a URL based on the following pattern: `{STREAMING_ENDPOINT}?x-adobe-flow-id={DATAFLOW_ID}`. For example, a constructed webhook URL may look like: `https://dcs.adobedc.net/collection/febc116d22ba0ea2868e9c93b199375302afb8a589617700991bb8f3f0341ad7?x-adobe-flow-id=439b3fc4-3042-4a3a-b5e0-a494898d3fb0`

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +Refer to the [DNL Customer.io] [Timeouts and failures](https://customer.io/docs/webhooks/#timeouts-and-failures) page.
Let's revise this to: "For information on guardrails, please refer to the [[!DNL Customer.io] timeouts and failures page](https://customer.io/docs/webhooks/#timeouts-and-failures).

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/customerio-webhook.md
> +Use the [URL](#get-streaming-endpoint-url) that was constructed in the [!UICONTROL WEBHOOK ENDPOINT] field.
Let's move the parts about webhooks out of Next steps and into its own heading between "get streaming endpoint URL" and "Next steps", maybe we can call it "Integrate Customer.io Webhooks" or something similar and update the link back in the connector overview page

Because this one is not Platform UI, let's replace "[!UICONTROL WEBHOOK ENDPOINT]" with [!DNL WEBHOOK ENDPOINT]

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/api/create/marketing-automation/customerio-webhook.md
> +| `baseConnectionId` | The base connection ID of [!DNL Customer.io]. This ID was generated in an earlier step. |
We can remove this line

2023-02-22 22:01 UTC, carlojavier commented on help/sources/tutorials/api/create/marketing-automation/customerio-webhook.md
> +To schedule an ingestion, you must first set the start time value to epoch time in seconds. Then, you must set the frequency value to one of the five options: `once`, `minute`, `hour`, `day`, or `wee
Let's remove this part. Looks like we won't need it for streaming. I will also remove it from the template.

2023-02-22 22:01 UTC, carlojavier commented on help/sources/connectors/marketing-automation/customerio-webhook.md
> +A validated [!DNL Customer.io] account. If you do not have one already see the [[!DNL Customer.io] signup page](https://fly.customer.io/signup) to register and create your account.
(Pls let me know if the meaning here gets altered entirely) Let's remove "validated" here because it can be confusing when read with the following sentence, that also talks about getting your account validated. If it's fine to remove, let's go with:
"A [!DNL Customer.io] account. If you do not have one already, read the [[!DNL Customer.io] signup page](https://fly.customer.io/signup) to register and create your account.

2023-02-22 22:01 UTC, carlojavier commented on help/sources/connectors/marketing-automation/customerio-webhook.md
> +Later, after you set up the [!DNL Customer.io] source, you will set up a Reporting Webhook to inform Platform about [!DNL Customer.io] events as explained in the [Get your streaming endpoint URL](../
This feels like a big step so let's have it as an H3:

### Set up Reporting Webhook

Once you have successfully created your dataflow, you must set up a Reporting Webhook to inform Platform about [!DNL Customer.io] events. Webhooks can notify you immediately when customer attributes change or when people open your messages, and send this information to your [!DNL Customer.io] source. For more information, read the tutorials on [getting your streaming endpoint URL](../../tutorials/ui/create/marketing-automation/customerio-webhook.md#set-up-webhook) and [setting up a Customer.io Webhook](../../tutorials/ui/create/marketing-automation/customerio-webhook.md#next-steps).

2023-02-23 11:50 UTC, mohan-h commented on help/sources/connectors/marketing-automation/customerio-webhook.md
> +Later, after you set up the [!DNL Customer.io] source, you will set up a Reporting Webhook to inform Platform about [!DNL Customer.io] events as explained in the [Get your streaming endpoint URL](../
Thanks

2023-02-23 20:57 UTC, carlojavier commented
@mohan-h thanks for the revisions. This PR has been copied over to our internal repo

2023-02-23 23:42 UTC, merged