Mailchimp tags dest
AdobeDocs/experience-platform.en pull request #194
Opened 2023-03-28 06:02 UTC by mohan-h

Initial commit

2023-03-30 09:13 UTC, vfalon requested changes
Hey @mohan-h ! Thanks for submitting the Mailchimp documentation. It looks great, just a few comments to address before we get it ready.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +title: Mailchimp Tags
Is Tags supposed to be capitalized? Looking at their website (https://mailchimp.com/help/getting-started-tags/#About_tags), it seems it's all lowercase. Let's clarify if it should be `Mailchimp Tags` or `Mailchimp tags` both in the docs and in the UI.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +This [!DNL Adobe Experience Platform] [destination](/help/destinations/home.md) leverages the [[!DNL Mailchimp Batch subscribe or unsubscribe API]](https://mailchimp.com/developer/marketing/api/lists
Lower case "batch subscribe"

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The sales department of an organization wants to broadcast an email based marketing campaign to a curated list of contacts. The organizations marketing team can add new contacts or update tags of exi
organization's

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The sales department of an organization wants to broadcast an email based marketing campaign to a curated list of contacts. The organizations marketing team can add new contacts or update tags of exi
Let's break up the second phrase into multiple sentences. It's rather difficult to follow what you mean there.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +### Prerequisites in [!DNL Mailchimp Tags] {#prerequisites-destination}
I think there is a terminology confusion here. I don't think `Mailchimp Tags` is an actual name of a product, but please double check this with the team. Instead, my understanding is that tags are a feature of the Mailchimp platform.

So this heading would be ### Prerequisites in [!DNL Mailchimp], since customers need to log in to their Mailchimp account, where they can configure their tags.

Again, please double check if this is correct.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +Next you need to identify your Mailchimp domain, to do this log in to your [!DNL Mailchimp] account and check the URL in your browser.
Let's break this phrase up. 

Next you need to identify your Mailchimp domain. To do this, log in to your [!DNL Mailchimp] account and check the URL in your browser.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +You’ll notice a value similar to *`us19`.admin.mailchimp.com*, the `us19` prefix is the value you will require.
You’ll notice a value similar to *`us19`.admin.mailchimp.com*. Write down the prefix (`us19` in this example). You will need this prefix when connecting to the destination.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +Refer to the [!DNL Mailchimp] [rate limits](https://mailchimp.com/developer/marketing/docs/fundamentals/#api-limits) which details the limits imposed by the [!DNL Mailchimp] API.
Refer to the [!DNL Mailchimp] [rate limits](https://mailchimp.com/developer/marketing/docs/fundamentals/#api-limits) for detailed information about the limits imposed by the [!DNL Mailchimp] API.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Email | Contact Email Address | Mandatory |
Contact email address

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +To authenticate to the destination, select **[!UICONTROL Connect to destination]**. You will be navigated to the [!DNL Mailchimp Log in and authorize] page. Enter your [!DNL Mailchimp] account creden
You will be redirected to the [!DNL Mailchimp] authorization page.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +To authenticate to the destination, select **[!UICONTROL Connect to destination]**. You will be navigated to the [!DNL Mailchimp Log in and authorize] page. Enter your [!DNL Mailchimp] account creden
"Enter your [!DNL Mailchimp] account credentials and select [!DNL Log In]."

I believe there is a screenshot missing here. The image below shows the Connect to destination part, not the Mailchimp log in part.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +If the details provided are valid, the UI displays a message: *You successfully connected to Mailchimp Tags account* message and a **[!UICONTROL Connected]** status with a green check mark, you can t
If the details provided are valid, the Platform UI displays the following message along with a **[!UICONTROL Connected]** status with a green check mark: *[!DNL You successfully connected to Mailchimp Tags account]*. You can then proceed to the next step.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| **[!UICONTROL Audience List ID]** | After you provide the value of your `Data Center` entries in this select dropdown are automatically populated with the audience names from your account. You need
After you enter your [!UICONTROL Data Center] prefix, this dropdown is automatically populated with the audience names from your account. Select the audience that you want to update with data from Platform.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +1. In the **[!UICONTROL Select source field]** window, choose the **[!UICONTROL Select identity namespace]** and select `Email`.
In the **[!UICONTROL Select source field]** screen, choose  **[!UICONTROL Select identity namespace]** and select the `Email` identity namespace.

Also, let's add a screenshot for this step.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +1. In the **[!UICONTROL Select target field]** window, choose the **[!UICONTROL Select identity namespace]** and select `Email`.
In the **[!UICONTROL Select target field]** screen, choose **[!UICONTROL Select identity namespace]** and select the `Email` identity namespace.

Also, let's add a screenshot for this step.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +1. Log in to the [[!DNL Mailchimp]](https://login.mailchimp.com/) website. Then navigate to the **[!DNL Audience]** > **[!DNL All Contacts]** page and check if the contacts from the segment have been
Log in to your [[!DNL Mailchimp]](https://login.mailchimp.com/) account.

2023-03-30 09:13 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +Refer to the [[!DNL Mailchimp] Errors](https://mailchimp.com/developer/marketing/docs/errors/) page for a comprehensive list of status and error codes with explanations.
Refer to the [!DNL Mailchimp] [errors page](https://mailchimp.com/developer/marketing/docs/errors/)

2023-03-30 10:30 UTC, mohan-h commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +### Prerequisites in [!DNL Mailchimp Tags] {#prerequisites-destination}
Correct `Mailchimp Tags` is not a product however here we are referring to prerequisites for the destination. Have added the word destination to make it clearer and read as `### Prerequisites for the [!DNL Mailchimp Tags] destination {#prerequisites-destination}`. Note the subsequent sub-heading `#### You need to have a [!DNL Mailchimp] account {#prerequisites-account}` refers to `Mailchimp`.

2023-03-31 05:27 UTC, mohan-h commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +title: Mailchimp Tags
It is `T`ags.

2023-10-11 10:08 UTC, vfalon requested changes
@mohan-h I've reviewed the latest changes and left some more comments to address. Please let me know if you have any questions. Thank you!

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The sales department of an organization wants to broadcast an email based marketing campaign to a curated list of contacts. The lists of contact are received in batches from different offline sources
Line 21: "starts building the Experience Platform segment's "  ---> "starts building the Experience Platform audiences"

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The sales department of an organization wants to broadcast an email based marketing campaign to a curated list of contacts. The lists of contact are received in batches from different offline sources
"The lists of contact are received" ---> "The lists of contacts is received"

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The sales department of an organization wants to broadcast an email based marketing campaign to a curated list of contacts. The lists of contact are received in batches from different offline sources
"After sending these segments to [!DNL Mailchimp Tags] if any contacts do not exist in the selected [!DNL Mailchimp] audience they get added with an associated tag having the segment name the contact belongs to."

Please rephrase to:

"After sending these audiences to [!DNL Mailchimp Tags], if any contacts do not exist in the selected [!DNL Mailchimp] audience, they get added with an associated tag which includes the audience name the contact belongs to."

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +If you do not have your **API key**, Sign in to your account and refer to the [[!DNL Mailchimp] Generate your API key](https://mailchimp.com/developer/marketing/guides/quick-start/#generate-your-api-
Line 43: lowercase s in "Sign in"

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +If you do not have your **API key**, Sign in to your account and refer to the [[!DNL Mailchimp] Generate your API key](https://mailchimp.com/developer/marketing/guides/quick-start/#generate-your-api-
Please reword this to:

If you do not have your **API key**, sign in to your [!DNL Mailchimp] account and refer to the [!DNL Mailchimp] documentation on [how to generate your API key](https://mailchimp.com/developer/marketing/guides/quick-start/#generate-your-api-key).

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +#### Identify [!DNL Mailchimp] data center {#identify-data-center}
Line 51: Identify your [!DNL Mailchimp] data center {#identify-data-center}

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +The value is the first part of the URL you see in your browser. If the URL is *https://`us14`.mailchimp.com/account/api/*, then the data center is `us14`.
Line 55: The data center ID is the first section of the URL you see in your browser. If the URL is *https://`us14`.mailchimp.com/account/api/*, then the data center ID is `us14`.

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +It's also appended to your API key in the form *key-dc*; if your API key is `0123456789abcdef0123456789abcde-us14`, then the data center is `us14`.
Line 57: The data center ID is also appended to your API key in the form *key-dc*. For example, if your API key is `0123456789abcdef0123456789abcde-us14`, then the data center is `us14`.

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +Write down the data center value *(`us14` in this example)*, you need this value when you [fill in destination details](#destination-details).
Line 59: Write down the data center value *(`us14` in this example)*. You will need this value when you [fill in the destination details](#destination-details).

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Email | Contact email Address | Mandatory |
Line 73: Update the description to: The email address of the contact.

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Audience origin | Supported | Description |
Please update the supported audiences table to:


| Audience origin | Supported | Description | 
---------|----------|----------|
| [!DNL Segmentation Service] | ✓ | Audiences generated through the Experience Platform [Segmentation Service](../../../segmentation/home.md).|
| Custom uploads | X | Audiences [imported](../../../segmentation/ui/overview.md#import-audience) into Experience Platform from CSV files. |

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Export type | **[!UICONTROL Profile-based]** | <ul><li>You are exporting all members of a segment, together with the desired schema fields *(for example: email address, phone number, last name)*, a
Line 93: "You are exporting all members of a segment, " --> "You are exporting all members of an audience, "

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Export type | **[!UICONTROL Profile-based]** | <ul><li>You are exporting all members of a segment, together with the desired schema fields *(for example: email address, phone number, last name)*, a
"For each selected segment in Platform, the corresponding [!DNL Mailchimp Tags] segment status gets updated with its segment status from Platform." --> "For each audience selected in Platform, the corresponding [!DNL Mailchimp Tags] segment status gets updated with the audience status from Platform."

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| Export frequency | **[!UICONTROL Streaming]** | Streaming destinations are "always on" API-based connections. As soon as a profile is updated in Experience Platform based on segment evaluation, the
"As soon as a profile is updated in Experience Platform based on segment evaluation,"  --> "As soon as a profile is updated in Experience Platform based on audience evaluation,"

2023-10-11 10:08 UTC, vfalon commented on help/destinations/catalog/email-marketing/mailchimp-tags.md
> +| **[!UICONTROL Username]** | Your [!DNL Mailchimp Interest Categories] username. |
Your [!DNL Mailchimp Interest Categories] username.

I believe this should say Mailchimp Tags.

2024-02-20 15:59 UTC, merged