SAP Hybris (Subscription Billing) source
AdobeDocs/experience-platform.en pull request #213
Opened 2023-06-14 07:47 UTC by mohan-h

Initial commit

2023-06-14 21:00 UTC, carlojavier requested changes
Thanks @mohan-h few edits, but looking good!

2023-06-14 21:00 UTC, carlojavier commented on help/sources/connectors/crm/sap-hybris.md
> +# (Beta) [!DNL SAP Hybris]
Since we have the badge system now, we can remove the "(Beta)" label in the header

2023-06-14 21:00 UTC, carlojavier commented on help/sources/connectors/crm/sap-hybris.md
> +[[!DNL SAP Hybris]](https://www.sap.com/india/products/acquired-brands/what-is-hybris.html) is a cloud-based e-commerce platform solution for B2B and B2C enterprises is now available as part of the S
Let's rephrase the beginning of this to: "SAP Hybris, a cloud-based e-commerce platform solution..."

2023-06-14 21:00 UTC, carlojavier commented on help/sources/connectors/crm/sap-hybris.md
> +A [!DNL SAP Subscription Billing] account. You must contact your [!DNL SAP] account manager to obtain a valid [!DNL SAP Subscription Billing] account if you do not already have one. Refer to the [[!D
Let's have this bulleted like the next item. So:

- "A [!DNL SAP Subscription Billing]account. If you do not already have a valid billing account, then please contact your [!DNL SAP] account manager. For more information, refer to the [[!DNL SAP] Platform Configuration document](https://help.sap.com/doc/5fd179965d5145fbbe7f2a7aa1272338/latest/en-US/PlatformConfiguration.pdf)."

2023-06-14 21:00 UTC, carlojavier commented on help/sources/connectors/crm/sap-hybris.md
> +* `url`, matching the pattern similar to `https://subscriptionbilling.authentication.eu10.hana.ondemand.com`. This value will be used to obtain the values for `region` and `tokenEndpoint` when you [C
Slight structural adjustment to the bullet system here:

- Service key. The Service key allows you to access a service instance. The [!DNL SAP Hybris] service key requires the following:
- Client ID
- Client secret
- URL. The URL pattern is as follows: `https://subscriptionbilling.authentication.eu10.hana.ondemand.com`. This value will be used later to obtain values for...

(Note: client ID, secret, and URL should be indented, but Git won't let me do it in the comment)

2023-06-14 21:00 UTC, carlojavier commented on help/sources/connectors/crm/sap-hybris.md
> ++++ View Service Key
"View service key example"

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/ui/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> +exl-id: 45840d7e-4c19-4720-8629-be446347862d
Need to remove the exl-id, this should auto-generate once we publish

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/ui/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> +# (Beta) Create a [!DNL SAP Hybris] source connection in the UI
Same as other docs, lets remove "(Beta)" from the header and add "badge: Beta" in the metadata

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/ui/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> +Refer to the [!DNL SAP Hybris] [documentation](https://help.sap.com/docs/CLOUD_TO_CASH_OD/987aec876092428f88162e438acf80d6/c5fcaf96daff4c7a8520188e4d8a1843.html) if you need any guidance.
reformat link and text to: "For more information, please refer to the [[!DNL SAP Hybris] documentation](https://help.sap.com/docs/CLOUD_TO_CASH_OD/987aec876092428f88162e438acf80d6/c5fcaf96daff4c7a8520188e4d8a1843.html)."

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/ui/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> ++++ View Service Key
Should be "View schema example"

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/ui/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> +Based on the `object_type` selection *(either `customers` or `contacts`)* and your schema the mappings would be as below. Setup the desired mappings before proceeding to the next stage.
need a comma after "schema" and "Setup" in the second sentence should be "Set up"

2023-06-14 21:00 UTC, carlojavier commented on help/sources/tutorials/api/create/crm/sap-hybris-subscription-billing-customers-and-contacts.md
> +# (Beta) Create a source connection and dataflow for [!DNL SAP Hybris] using the Flow Service API
Similar to the other docs, lets remove "(Beta)" from the title and add "badge: Beta" in the metadata

2023-06-15 09:45 UTC, mohan-h commented on help/sources/connectors/crm/sap-hybris.md
> +* `url`, matching the pattern similar to `https://subscriptionbilling.authentication.eu10.hana.ondemand.com`. This value will be used to obtain the values for `region` and `tokenEndpoint` when you [C
Have reworded your suggestion from `The Service key allows you to access a service instance` to `The Service key allows you to access the [!DNL SAP Subscription Billing] API through Platform`

2023-06-15 09:51 UTC, mohan-h commented
Thanks @carlojavier have updated, note the dev team are still awaiting the confirmation on the connector naming so the connector name and images might change.

2023-06-20 00:25 UTC, merged