Bhealy21 patch 2
AdobeDocs/experience-platform.en pull request #251
Opened 2023-09-19 19:48 UTC by bhealy21

2023-09-20 09:21 UTC, vfalon requested changes
@bhealy21 Thanks for the updates. However, it seems some of my comments have not been addressed yet. I see you also created a new PR. This is not needed.

Please review the comments I left in this PR, and _commit the changes to this same PR. (https://github.com/AdobeDocs/experience-platform.en/pull/251/)_ This way we can track the comments and see if there's all resolved.

I will close the previous PR and we'll work on this one.

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
>  # [!DNL LiveRamp - Distribution] connection {#liveramp-onboarding}
Line 6: Please remove {#liveramp-onboarding}

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* [[[!DNL Roku]](#roku)
Line 32: There's an extra `[` on the Roku link

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +>title="SeatId"
>title="SeatId"

The UI field labels should not read like code variables. This should be called "Seat ID" in the customer data fields, labels, and the popover. Please update this to the correct formatting.

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +>abstract="Magnite DV+ "seatId" provided by your Magnite account manager"
>abstract="Magnite DV+ Seat ID provided by your Magnite account manager"

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL SeatId]**: Magnite DV+ "seatId" provided by your Magnite account manager
Please update these fields to Partner ID and Seat ID, in both the docs and the destination config.

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL Your Company Name]**: Your Company Name, as you would like it to be shown to the destination partner. Do not use spaces or special characters.
Line 132: No need for camelcase in the description: "Your company name, as you would like it to be shown to the destination partner. Do not use spaces or special characters."

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL Client]**: Your Client name, as you would like it to be shown to the destination partner. Use your company name. Do not use spaces or special characters.
Line 225: No need for capital C in "Client name" description

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +>abstract="Your Client name, as you would like it to be shown to the destination partner. Use your company name. Do not use spaces or special characters."
Line 219: Lowercase C in the abstract.

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +>title="PartnerId"
Line 231: Partner ID

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL PartnerId]**: The Rubicon Project Partner ID associated with the publisher who owns the segment/data. Please contact your Rubicon Project account representative if unsure of the value
Line 243: Partner ID

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL Client]**: The name of your company/distribution account as you would like it to appear to the partner. Use your company name by default, but please contact your partner account rep i
Line 288: [!UICONTROL Client]: The name of your company/distribution account as you would like it to appear to the partner. Use your company name by default. If unsure, please contact your partner account representative. Do not use spaces or special characters (e.g. Company_Name).

2023-09-20 09:21 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL Segment Type]**: The segment type (1st Party only available at this time).
Line 370: Please update the spelling to "Segment type" in both destination config and docs. Capitalization of fields should be consistent across the UI.

2023-09-20 09:42 UTC, vfalon requested changes

2023-09-20 09:42 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +>id="company_name"
Line 124: This ID does not follow the correct format. Please update this to:

>id="platform_destinations_liveramp_distribution_ampersand_company_name"
>title="Your company name"
>abstract="Your company name, as you would like it to be shown to the destination partner. Do not use spaces or special characters."

Please update this tooltip ID in the destination config, too. It's using the wrong format:


 "tooltip": {
            "id": "company_name",
            "fallbackUrl": "https://www.adobe.com/go/destinationsliveramp-en"
          }

Also, unrelated to the docs, the **fallbackUrl** in the destination config seems to have been altered. The correct link is  https://www.adobe.com/go/destinations-liveramp-distribution-en

2023-09-21 22:16 UTC, bhealy21 commented
Hey @vfalon .  I believe all changes have now been committed directly to this PR.  Can you please take a look and let me know if this is reflected on your end?

2023-09-25 11:48 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL SeatId]**: Magnite DV+ "seatId" provided by your Magnite account manager
@bhealy21 I see you updated this in the destination config, but not in the documentation. Please update these fields to Seat ID and Partner ID.

2023-09-25 11:49 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL PartnerId]**: The Rubicon Project Partner ID associated with the publisher who owns the segment/data. Please contact your Rubicon Project account representative if unsure of the value
@bhealy21 Please update this to Partner ID.

2023-09-25 11:50 UTC, vfalon commented on help/destinations/catalog/advertising/liveramp-distribution.md
> +* **[!UICONTROL Segment Type]**: The Segment type (1st Party only available at this time).
Line 370: **[!UICONTROL Segment type]**: The segment type (1st Party only available at this time).

2023-09-25 11:51 UTC, vfalon requested changes
Hey @bhealy21 , thanks for the updates. Some of my comments were still not addressed. Please review my latest comments and let me know if you have any questions.

2023-09-29 15:40 UTC, merged