Update onetrust.md
AdobeDocs/experience-platform.en pull request #27
Opened 2022-03-13 19:31 UTC by jmaniot

Added tutorial on how to establish a data-flow from OneTrust to Adobe Experience Platform.

2022-03-17 17:39 UTC, carlojavier requested changes
Hey @jmaniot looks great! thanks for following the template, two small comments regarding the very large JSON response in the Explore section here. Please address them and then I think we can move forward to the next step. Let me know if you have any questions! Thanks!

2022-03-17 17:39 UTC, carlojavier commented on help/sources/tutorials/api/create/consent-and-preferences/onetrust.md
> +
This response sample is quite large, but we can incorporate it in a collapsible section, by wrapping it in "+++" at the top, just a space above the ``` and also at the bottom, a space below the ```. So it would look like:
+++Click me

```json
[json text here]
```
+++

Here is a doc for reference: https://experienceleague.adobe.com/docs/authoring-guide-exl/using/markdown/syntax-style-guide.html?lang=en#collapsible-sections

2022-03-17 17:39 UTC, carlojavier commented on help/sources/tutorials/api/create/consent-and-preferences/onetrust.md
> +
Once the JSON response below is in a collapsible section, let's also add a [!NOTE] here to let the user know that "The JSON response payload below is hidden for brevity. Select **Click me** to see the response payload."

2022-03-20 07:27 UTC, jmaniot commented on help/sources/tutorials/api/create/consent-and-preferences/onetrust.md
> +
Thanks for the heads up. Updated the structure.

2022-03-20 07:28 UTC, jmaniot commented on help/sources/tutorials/api/create/consent-and-preferences/onetrust.md
> +
Done .

2022-03-22 01:43 UTC, carlojavier commented
Thanks @jmaniot ! I've copied the changes over to our internal repo for publishing on release day. Thanks for following the template! Feel free to close this PR.

2022-04-12 20:00 UTC, merged