Oracle NetSuite Activities Source initial commit
AdobeDocs/experience-platform.en pull request #281
Opened 2023-11-26 12:27 UTC by mohan-h

2023-12-11 20:57 UTC, carlojavier requested changes
@mohan-h thanks for the submission! I've left some comments for you

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +    * You will need your **[!DNL NetSuite] Account ID**. Refer to the [Finding your NetSuite Account ID](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_1498754928.html#Finding-
I think we just need one of these bullet points. We can just keep the first one.

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +* Have an active subscription to any product.
I think we can revise this to: "An active subscription to any [!DNL Oracle NetSuite] product." Or should it be "... any [!DNL Oracle] product."

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +    * To access the [!DNL Oracle NetSuite] API's, You will need a **Client ID** and **Client secret**, follow the [OAuth 2.0](https://docs.oracle.com/en/cloud/saas/NetSuite/ns-online-help/chapter_157
replace "... the below:" with "... the following:"

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +        * Assigned Users to the Oauth 2.0 Roles, and created Integration records
We can revise some of these to sentence-case:
- Ensure your [!DNL Oracle NetSuite] administrator has enabled the OAuth 2.0 feature.
- Set up roles.
- Assign users to OAuth 2.0 roles and create integration records.

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +    * You will also need to generate an **Access token** and a **Refresh Token**. Refer to the [OAuth 2.0 Authorization Code Grant Flow](https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/
- we can refer to "access token" and "refresh token" in sentence case in this context
- sentence case for both "step one" and "step two"

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +| accessTokenUrl | The [!DNL NetSuite] Access Token URL. This takes the form shown alongside. | <code>https://<NETSUITE_ACCOUNT_ID>.suitetalk.api.netsuite.com<br>/services/rest/auth/oauth2/v1/token</
sentence case for mentions of "step two"

2023-12-11 20:57 UTC, carlojavier commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +> After a Refresh token expires you must create a New Account in Platform with updated tokens.
sentence case for "refresh token"

2023-12-11 20:57 UTC, carlojavier commented on help/sources/tutorials/api/create/marketing-automation/oracle-netsuite-activities.md
> +```json
Let's wrap this response in a collapsable (+++) and add "Select to view JSON payload" as a prompt

2023-12-11 20:57 UTC, carlojavier commented on help/sources/tutorials/api/create/marketing-automation/oracle-netsuite-entities.md
> +A successful response returns a structure as below.
Let's wrap these responses in a collapsable as well (+++), they should work within the tabs

2023-12-11 20:57 UTC, carlojavier commented on help/sources/tutorials/api/create/marketing-automation/oracle-netsuite-entities.md
> +
Let's add a collapsable here

2023-12-11 20:57 UTC, carlojavier commented on help/sources/tutorials/ui/create/marketing-automation/oracle-netsuite-activities.md
> +| accessTokenUrl | The [!DNL NetSuite] Access Token URL. This takes the form shown alongside. | https://<ACCOUNT_ID>.suitetalk.api.netsuite.com/services/rest/auth/oauth2/v1/token |
Let's reformat the placeholder values in the examples from "<EXAMPLE>" to "{EXAMPLE}" please apply throughout the other docs too

2023-12-12 09:50 UTC, mohan-h commented on help/sources/connectors/marketing-automation/oracle-netsuite.md
> +        * Assigned Users to the Oauth 2.0 Roles, and created Integration records
Have merged 1 & 2

2024-01-25 20:29 UTC, merged