Documentation for Zeta Marketing Platform destination
AdobeDocs/experience-platform.en pull request #299
Opened 2024-01-19 19:24 UTC by hsaraiya

Added:
* a new file `zetamarketingplatform.md` for our integration with Adobe Experience Platform
* supporting screenshots
@adobe-documentation-team, please review.

2024-01-19 19:37 UTC, hsaraiya commented
Adobe CLA signed

2024-02-07 15:39 UTC, vfalon requested changes
@hsaraiya thank you for the docs submission! There are some changes that we need you to address before we move forward with this destination. Please see my comments and let me know if you have any questions.

Looking forward to see the updates!

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +The Zeta Marketing Platform, henceforth ZMP, is a cloud-based system with the tools to help you acquire, grow, and retain customers more efficiently, powered by intelligence (proprietary data and AI)
Please avoid phrasing like "henceforth" in documentation. Let's rephrase that part as "The Zeta Marketing Platform (ZMP) is a cloud-based system which helps you acquire [...]"

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +description: The Zeta Marketing Platform, henceforth ZMP, is a cloud-based system with the tools to help you acquire, grow, and retain customers more efficiently, powered by intelligence (proprietary
Please avoid phrasing like "henceforth" in documentation. Let's rephrase that part as "The Zeta Marketing Platform (ZMP) is a cloud-based system which helps you acquire [...]"

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +### Use case #1 {#use-case-1}
Please update the use case headings to something that gives readers an overview of what the use case is about.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +With the ZMP connector available in Adobe Experience Platform, you can seamlessly synchronize your audiences from Experience Platform to the ZMP.
Is the destination card in the Experience Platform UI called "ZMP"? If not, please refer to the connector by its full name (Zeta Marketing Platform).

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +An advertiser wants to target users in audiences with ads through the Zeta DSP as the user interacts with their brands. More information on the Zeta DSP and other DSPs that the ZMP supports can be fo
I strongly suggest replacing ZMP with Zeta Marketing Platform. This phrase sounds like a convoluted collection of acronyms which will confuse readers (More information on the Zeta DSP and other DSPs that the ZMP supports...).

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* Prior to setting up a new destination, please ensure the presence of a pre-existing shell customer list in your ZMP account. You will  be required to choose one of these customer lists as the desig
The first sentence in the prerequisites can be improved. What does "pre-existing shell customer list" mean? Does it mean "you need to create an empty customer list in your Zeta Marketing Platform account"?

If so, please rephrase that part along the lines of: "Before you set up a new connection to the Zeta Marketing Platform destination, you must create an empty customer list in your Zeta Marketing Platform account."

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* Prior to setting up a new destination, please ensure the presence of a pre-existing shell customer list in your ZMP account. You will  be required to choose one of these customer lists as the desig
Extra space in `"You will  be required"`

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* The username and password needed to configure the destination will be **api** and the **REST API Key**, which you can view in your ZMP account by navigating to **Settings** > **Integrations** > **K
Always use present tense in documentation, and use simple, short, phrases whenever possible:

Use the following credentials to configure the destination:

- Username: `api`
- Password:  Your ZMP REST API Key.  You can find your REST API Key by logging in to your ZMP account and navigating to **Settings** > **Integrations** > **Keys & Apps** section. See the [ZMP documentation]((https://knowledgebase.zetaglobal.com/zmp/integrations) for more details.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +The ZMP destination connector will allow you to map platform identities to identities that the ZMP accepts.
This sentence can be removed. It doesn't add any information to what is already below it.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +> Please note that it is mandatory to map a source identity namespace to ZMP's `uid` target identity so that the ZMP can uniquely differentiate each profile.
Move this note just above the table and after the introductory sentence.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +> Please note that it is mandatory to map a source identity namespace to ZMP's `uid` target identity so that the ZMP can uniquely differentiate each profile.
Avoid "please" in product documentation. Let's rephrase this note:

The ZMP destination requires you to map a source identity namespace to the ZMP `uid` target identity. This helps the Zeta Marketing Platform uniquely differentiate each profile.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +|uid|Unique id that ZMP uses to differentiate customer profiles|Mandatory|Choose the `Email` standard identity namespace if you want to identify unique profiles using their email addresses. Alternati
When referring to an ID as a noun, it must be capitalized:  "Unique ID that ZMP uses to..."

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +| [!DNL Segmentation Service] | ✓ | Audiences generated through the Experience Platform [Segmentation Service](../../../segmentation/home.md).|
Please leave the custom audiences entry in this table, as shown in the template: https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/document-destination/self-service-template.html?lang=en#supported-identities.

If it's not supported, mark it with an X in the Supported column, but don't remove the entry from the table.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* Enter the **[!UICONTROL Username]** as **api**
- **[!UICONTROL Username]**: `api`
- **[!UICONTROL Password]**: Your ZMP REST API Key. You can find your REST API Key by logging in to your ZMP account and navigating to Settings > Integrations > Keys & Apps section. See the [ZMP documentation]((https://knowledgebase.zetaglobal.com/zmp/integrations) for more details.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
Please update **[!UICONTROL ZMP Account Site Id]** to **[!UICONTROL ZMP Account Site ID]**.

Make sure to update the name in your destination configuration submission, too (and take another screenshot showing the correct casing for ID).

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
Your ZMP **Site Id** where you want to send your audiences to.  ->>> Your ZMP **Site ID** where you want to send your audiences to.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
You can view your Site Id by navigating -->>>  You can view your Site ID by navigating

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Segment]**: The customer list segment in your ZMP Site Id account that you want to be updated with the Platform audience.
list segment in your ZMP Site Id account --->>> list segment in your ZMP Site ID account

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* Select an identity namespace (custom or standard such as `Email`) as source field that uniquely identifies a profile in Adobe Experience Platform and [!DNL Zeta Marketing Platform].
Select a source identity namespace (custom or standard, such as `Email`) that uniquely identifies a profile in Adobe Experience Platform and [!DNL Zeta Marketing Platform].

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* (Mandatory) Select `uid` as the target identity that is mapped to the source identity namespace.
Phrasing issue here. Please update the first point to:

* (Mandatory) Select `uid` as the target identity to which you map a source identity namespace.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* (Optional) Select `email_md5_id` as the target identity that is mapped to the source identity namespace that represents email md5 values. In this scenario, map `uid` to a source identity namespace.
(Optional) Select `email_md5_id` as the target identity that is mapped to the source identity namespace that represents email md5 values. In this scenario, map `uid` to a source identity namespace.

Update to: 
(Optional) Select `email_md5_id` as the target identity to which you mapped the source identity namespace that represents email md5 values.


I don't understand the point of this sentence "In this scenario, map `uid` to a source identity namespace." My understanding is that `uid` mapping is mandatory either way. You already mentioned that at the previous bullet point.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* Select any other destination profile attribute names that need to be mapped to corresponding XDM source profile attributes.
Please rephrase this to "Select any additional target mappings if needed."

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +A successful audience syndication from experience platfrom to the ZMP will update the target customer list in the ZMP. The count as well as sample profiles in the target customer list will be exactly
A successful audience syndication from experience platfrom to the ZMP will update the target customer list in the ZMP. The count as well as sample profiles in the target customer list will be exactly equal to the number of identities that were successfuly activated from experience platform as shown below.

Please rephrase to:

A successful audience activation from Experience Platform to the ZMP updates the target customer list in the ZMP. The count and the sample profiles in the target customer list will be equal to the number of identities that were successfully activated.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +Each audience member that was syndicated from the experience platform will also be visible under **Audiences** > **People** in the ZMP.
Each audience member that was syndicated from the experience platform will also be visible under **Audiences** > **People** in the ZMP. 

Rephrase as:

Each audience member that was activated from Experience Platform will also be visible under **Audiences** > **People** in the ZMP.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +* [Zeta Knowledge Base](https://knowledgebase.zetaglobal.com/zmp/).
Remove the full stop at the end of this item.

2024-02-07 15:39 UTC, vfalon commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +title: Zeta Marketing Platform
A couple of file management issues:

- Please rename the doc page to `zeta-marketing-platform.md`.
- Please rename the `assets/catalog/data-management-platform/zmp-extension/` folder to `assets/catalog/data-management-platform/zeta-marketing-platform/`

2024-02-08 18:56 UTC, hsaraiya commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
@vfalon The identity is shown in the ZMP UI as `Id` (lowercase D). I'd prefer keeping it that way. Thoughts?

2024-02-08 18:58 UTC, hsaraiya commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
@vfalon We refer to site identity as `Site Id` (lowercase D) in our platform. Is this change needed?

2024-02-08 18:58 UTC, hsaraiya commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Account Site Id]**: Your ZMP **Site Id** where you want to send your audiences to. You can view your Site Id by navigating to **Settings** > **Integrations** > **Keys & Apps** se
@vfalon We refer to site identity as `Site Id` (lowercase D) in our platform. Is this change needed?

2024-02-08 19:01 UTC, hsaraiya commented on help/destinations/catalog/data-management/zetamarketingplatform.md
> +*  **[!UICONTROL ZMP Segment]**: The customer list segment in your ZMP Site Id account that you want to be updated with the Platform audience.
@vfalon We refer to site identity as `Site Id` (lowercase D) in our platform. Is this change needed?

2024-02-08 21:36 UTC, hsaraiya commented
> @hsaraiya thank you for the docs submission! There are some changes that we need you to address before we move forward with this destination. Please see my comments and let me know if you have any questions.
> 
> Looking forward to see the updates!

@vfalon Thank you for the exhaustive list and detailed recommendations. I have made all the changes requested except the one with Id v/s ID. I haven't "resolved" comments just in case you'd want to review.

2024-02-29 11:01 UTC, vfalon requested changes
@hsaraiya thanks for making the updates! There are a few more changes to make, but otherwise it looks great! Looking forward to see the final updates. Thanks!

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +* Before you set up a new connection to the Zeta Marketing Platform destination, you must create an empty customer list in your Zeta Marketing Platform account. You will be required to choose one of
"You will be required to choose one of these customer lists .... "

Please rephrase as "You must choose one of these customer lists...

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +|email_md5_id|Email MD5 that represents each customer profile|Optional|Choose this target identity when you aim to uniquely identify customer profiles using email MD5 values. In this case, set `uid`
Regarding the MD5 mapping: please add a sentence here explaining that if customers want to map email addresses to MD5, they must have the email addresses already in MD5 format in Experience Platform, since Platform does not convert plain text to MD5.

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +> As individual members are added or removed from the platform audience, updates will be sent to the ZMP to ensure that the destination customer list is synchronized accordingly.
Please capitalize Platform wherever it is referenced. Or use Experience Platform for even more clarity.

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +* **[!UICONTROL Password]**: Your ZMP REST API Key. You can find your REST API Key by logging in to your ZMP account and navigating to **Settings** > **Integrations** > **Keys & Apps** section. See t
` See the [ZMP documentation](https://knowledgebase.zetaglobal.com/zmp/integrations) for more details.`

There's an extra ( there that breaks the link.

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +* (Optional) Select `email_md5_id` as the target identity to which you mapped the source identity namespace that represents email md5 values.
On the row regarding MD5 mapping, please add a sentence explaining that if customers want to map email addresses to MD5, they must have the email addresses already in MD5 format in Experience Platform, since Platform does not convert plain text to MD5.

2024-02-29 11:01 UTC, vfalon commented on help/destinations/catalog/data-management/zeta-marketing-platform.md
> +![Identity mapping](../../assets/catalog/data-management-platform/zeta-marketing-platform/MappingExample.png)
Please follow the image naming format described in the authoring guide(https://experienceleague.adobe.com/docs/experience-platform/destinations/destination-sdk/document-destination/authoring-best-practices.html?lang=en#linking). 

Use: yourdestination-authentication-details.png, yourdestination-destination-details.png

Instead of `MappingExample.png` please use `mapping-example.png`.

Review your assets folder and change all the image names to the correct format.

2024-03-01 00:29 UTC, hsaraiya commented
@vfalon I have made all the above requested changes. Thank you!

2024-06-25 16:31 UTC, merged