Added edgeBasePath to config docs
AdobeDocs/experience-platform.en pull request #30
Opened 2022-03-16 17:10 UTC by littlebutty

2022-03-16 17:11 UTC, jfkhoury commented
@vfalon @srhoades-adobe This PR is ready for review and merge. Thanks!

2022-03-16 20:06 UTC, jonsnyder approved these changes

2022-03-16 20:36 UTC, srhoades-adobe requested changes

2022-03-16 20:36 UTC, srhoades-adobe commented on help/edge/fundamentals/configuring-the-sdk.md
> +Path after the edgeDomain used to commuincate and interact with Adobe services.  Often this would only change when not using the default production environment.
Please fix typo: commuincate > communicate

2022-03-17 15:28 UTC, vfalon commented
Closing the PR and merging from the internal repo.

2022-03-17 15:28 UTC, closed without merging