Documentation submission for the Magnite-Streaming: Batch Destination
AdobeDocs/experience-platform.en pull request #356
Opened 2024-06-18 16:04 UTC by akoelling

Submission for the Magnite Streaming: Batch destination. 

Note that the doc will call link to a document for a Real-time destination that is part of another PR, so that specific link will be broken until the other PR is merged. 

Will include PR in comments once it is made.

2024-06-18 16:05 UTC, akoelling commented
PR for the Real-time destination https://github.com/AdobeDocs/experience-platform.en/pull/357

2024-06-19 09:23 UTC, vfalon requested changes
@akoelling Thanks for splitting the info in the 2 new PRs. However, I am still seeing lots of issues with the docs, most of which originate from not following the documentation self-service template that we offer and require for all destination docs submissions.

You can find the template here: https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/document-destination/self-service-template#activate.

Instructions on how to author the docs based on the template are here: https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/document-destination/documentation-instructions.

Please review BOTH destinations and make sure you follow all the sections in the template, and do not remove any headings or notes. Those are all mandatory. The template clearly explains what you should and shouldn't remove from its sections.

Once you're resubmitted the docs, we'll continue with reviewing the actual content.

2024-06-21 16:37 UTC, vfalon requested changes
@akoelling Thanks for the updates on the batch page! There are still many things to refine before we can publish this. Please see my comments.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +# Magnite Streaming: Batch Destination connection {#magnite-streaming-batch-destination}
Magnite Streaming: Batch connection

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +This destination allows you to deliver Adobe CDP audiences to Magnite Streaming for advertising targeting and activation. Audiences activated via this destination are delivered daily in a batch. Post
Adobe Real-Time CDP audiences

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +## Overview {#overview}
This heading should include the information above it.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +Magnite Streaming also has another destination, called the Magnite Streaming: Real-Time destination. See [this doc](magnite-streaming.md) for more information about the Real-Time destination. This Re
I feel like the entire intro to this destination is confusing. As a reader who doesn't know anything about this destination, I don't understand what the difference between this destination and the real-time one is, and which one I should use, and why.

I suggest rephrasing the overview/intro in a much clearer way. It should answer these questions:

- What does this destination do?
- Why are there two Magnite destinations?
- When do I need this destination? Is it mandatory for all use cases or not?

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +*Any audience(s) activated via the Magnite Streaming: Real-Time destination must also use the Magnite Streaming: Batch destination, as the Batch delivery is meant to replace the Real-Time delivery to
- audience(s)  -> audiences

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +*You have activated an audience on the Magnite Streaming: Real-Time destination.*
No need for italics in the use cases.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +To use the Magnite destinations in the Adobe Experience Platform, you must first have a Magnite Streaming account. If you have a [!DNL Magnite Streaming] account, please reach out to your [!DNL Magni
No  "the" before Adobe Experience Platform

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +The Magnite Streaming: Batch destination can receive *any* identity sources from the Adobe CDP. Currently, this destination has three Target Identity fields for you to map to. Please note: *any* iden
he Magnite Streaming: Batch destination can receive *any* identity sources from Adobe Real-Time CDP.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +The Magnite Streaming: Batch destination can receive *any* identity sources from the Adobe CDP. Currently, this destination has three Target Identity fields for you to map to. Please note: *any* iden
Please use the supported identities intro from the template instead of the intro you provided: https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/document-destination/self-service-template#supported-identities

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +| magnite_deviceId_IDFA | Apple ID for Advertisers | Select this Target Identity when your source identity is an IDFA |
No need for capitalized "Target Identity" in the Consideration column.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +| Target Identity | Description | Consideration |
The column in the template (https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/document-destination/self-service-template#supported-identities) is called **Considerations**. You missed an "s".

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +## Supported Audiences {#supported-audiences}
Please use sentence case for headings, as provided by the template.

`Supported audiences {#supported-audiences}`

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +## Export Type and Frequency {#export-type-frequency}
Please use sentence case for headings, as provided by the template.

`Export type and frequency`

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +Once your destination usage has been approved and Magnite Streaming has shared your credentials, please follow the below steps to authenticate, map, and share data.
The "Connect to the destination" section is again missing the required parts in the template (https://experienceleague.adobe.com/en/docs/experience-platform/destinations/destination-sdk/document-destination/self-service-template#connect).

There's nothing wrong with adding extra information if it is really needed, but please do not remove what the template already provides. You removed the section about Permissions, which is REQUIRED.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +Locate the Magnite Streaming: Batch destination in the Adobe Experience catalog. Click the additional options button (\...) and then configure the destination connection/instance.
No need for this part "Locate the ..."

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +To create a new account, and authenticate it to the destination for the first time, fill in the required "S3 access key" and "S3 secret key" fields (provided to you via your account manager), and sel
No need for "To create a new account, and authenticate it to..."

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +To create a new account, and authenticate it to the destination for the first time, fill in the required "S3 access key" and "S3 secret key" fields (provided to you via your account manager), and sel
You do not "create a new account", you just provide an existing S3 account to log in to. It's only "new" in the sense that there is no destination connection created using that account yet.

Please rephrase this section and list the fields in bullet points, with the field names in UICONTROL tags, as such: `**[!UICONTROL S3 access key]**`

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +**Note:** Magnite Streaming's security policy requires a regular rotation of S3 keys. You should expect to update your account in the future with new S3 access and S3 secret keys. You only need to up
This sounds like an important callout.

First, please use the !NOTE formatting as shown in the authoring guide: https://experienceleague.adobe.com/en/docs/contributor/contributor-guide/writing-essentials/markdown#note-blocks.

Second, let's also add a link to this page, which describes how users can update an account: https://experienceleague.adobe.com/en/docs/experience-platform/destinations/ui/update-accounts

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +**Note:** If you plan to send multiple ID types (GAID, IDFA, etc.) using the Batch destination, a new destination connection/instance is required for each. Please contact your Magnite Account represe
Please use the Note formatting as shown here https://experienceleague.adobe.com/en/docs/contributor/contributor-guide/writing-essentials/markdown#note-blocks

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +### Enable Alerts {#enable-alerts}
`### Enable alerts {#enable-alerts}`

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +Once the destination connection/instance has been created, you will be shown the audience activation flow. The following process walks through how to activate audiences using the Magnite Streaming Ba
Remove everything from  "Once the destination connection/instance has been created" all the way to the mapping step.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +#### Step 3: Map your source device ID to a magnite streaming device ID
This is not a step 3. Remove the numbering,

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +In the "SOURCE FIELD", you can select any attribute or identity for your devices. In this example, we've selected a custom IdentityMap called "DeviceId"
Replace all mentions of SOURCE FIELD and TARGET FIELD with:

`**[!UICONTROL Source field]**`

`**[!UICONTROL Target field]**`

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +In this example, we've selected the TARGET FIELD: magnite_deviceId_CUSTOM, because our SOURCE FIELD was definied as a custom IdentityMap: DeviceID.
Typo: definied.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +**Note:** If you plan to send/map multiple ID types (GAID, IDFA, etc.) using the Batch destination, a new destination connection/instance is required for each. Please contact your Magnite Account rep
Please use the correct note formatting: https://experienceleague.adobe.com/en/docs/contributor/contributor-guide/writing-essentials/markdown#note-blocks

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +When you're done selecting your mapping, select **[!UICONTROL Next]**
This part about file name and export settings is already documented in the activation guide for batch, which you already linked to. Remove everything here except for the mapping considerations.

The screenshot with all the markings on it also looks extremely messy. Please explain the important callouts clearly in text, without writing instructions on the screenshot.

2024-06-21 16:37 UTC, vfalon commented on help/destinations/catalog/advertising/magnite-batch.md
> +#### Step 4: Review and confirm the Destination Activation configuration
No need for this section. This is already documented in the batch activation guide.

2024-06-21 18:25 UTC, jakeseawell commented
@vfalon Ready for re-review. Thanks!

2024-06-21 19:05 UTC, jessparke commented
adding @vgiurgiu as well

2024-06-24 10:10 UTC, vgiurgiu reviewed
Please see a few more comments, and also there are a few comments from @vfalon left unaddressed.

2024-06-24 10:10 UTC, vgiurgiu commented on help/destinations/catalog/advertising/magnite-batch.md
> +To recap: If you only want to deliver Adobe Real-Time CDP audiences once per day, you will use the Magnite: Streaming Batch destination only, and audiences will be delivered once per day. If you want
this entire explanation between lines 12 - 18 is excellent and now I really understand the different purpose of the two connectors. could you reuse the part "However, if you want and/or need to deliver audiences in real-time, you will need to use the Magnite: Streaming Real-Time destination. When using the Real-Time destination, Magnite: Streaming will receive audiences in real-time, but we can only store real-time audiences temporarily in our platform, and they will be removed from our system within a couple days. For this reason, if you want to use the Magnite: Streaming Real-Time destination, you will ALSO need to use the Magnite: Streaming Batch destination - each audience that you activate to the Real-Time destination, you also need to activate to the Batch destination." in the other connector page as well please so that readers going to that page have the same information?

2024-06-24 10:10 UTC, vgiurgiu commented on help/destinations/catalog/advertising/magnite-batch.md
> +*Any audiences activated via the Magnite Streaming: Real-Time destination must also use the Magnite Streaming: Batch destination, as the Batch delivery's data is meant to replace/persist the Real-Tim
reiterating the comment from @vfalon above, no need to use italics `*something*` in use cases

2024-06-24 10:10 UTC, vgiurgiu commented on help/destinations/catalog/advertising/magnite-batch.md
> +| magnite_deviceId_GAID | Google Advertising ID | Select this Target Identity when your source identity is a GAID |
wondering how come the batch destination has three target identities to map to and the streaming real-time destination only has the device_id target field to map to?

2024-06-24 13:21 UTC, jessparke commented on help/destinations/catalog/advertising/magnite-batch.md
> +To recap: If you only want to deliver Adobe Real-Time CDP audiences once per day, you will use the Magnite: Streaming Batch destination only, and audiences will be delivered once per day. If you want
I added this to the streaming documentation.

2024-06-24 13:22 UTC, jessparke commented on help/destinations/catalog/advertising/magnite-batch.md
> +*Any audiences activated via the Magnite Streaming: Real-Time destination must also use the Magnite Streaming: Batch destination, as the Batch delivery's data is meant to replace/persist the Real-Tim
Updated.

2024-06-24 13:24 UTC, jessparke commented
@vgiurgiu The batch destination is updated.

2024-06-24 15:04 UTC, jakeseawell commented on help/destinations/catalog/advertising/magnite-batch.md
> +| magnite_deviceId_GAID | Google Advertising ID | Select this Target Identity when your source identity is a GAID |
In our new Streaming pipeline, we don't care about the deviceType of the deviceID coming through the system. Even if we did capture the deviceType, we (Magnite) wouldn't do anything with that information. Therefore, for simplicity, we removed the 3 target identities that identify deviceType, and replaced it with just the one field we care about: deviceID. However, our Batch pipeline, which was built before this integration, does care about deviceType. Therefore, in order to support customers that want this information captured, we have the three target identities, which we use on our end to identify deviceType. It was a decision whether to make the two destinations have the same mapping, which would make the Streaming destination a bit more complicated and contain unused information, or to give the two destinations different mapping steps, with the consequence of the Streaming destination being simpler, and all data sent being useful. And we went with the latter choice. Hopefully that is a clear-enough explanation?

2024-06-26 08:34 UTC, vgiurgiu commented on help/destinations/catalog/advertising/magnite-batch.md
> +| magnite_deviceId_GAID | Google Advertising ID | Select this Target Identity when your source identity is a GAID |
Understood, thank you for the explanation!

2024-06-28 21:05 UTC, merged