Zendesk (Source) initial commit
AdobeDocs/experience-platform.en pull request #57
Opened 2022-05-17 18:19 UTC by mohan-h

Zendesk (Source) initial commit

2022-05-18 04:21 UTC, carlojavier requested changes
Hey @mohan-h thanks for this! Added some comments, just some small changes. Thanks!

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +exl-id:
We can remove "exl-id" here as it is auto-generated upon publishing

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +This [!DNL Adobe Experience Platform] [!DNL sources connector](https://experienceleague.adobe.com/docs/experience-platform/sources/home.html?lang=en) leverages the [!DNL Zendesk Search API > Export S
We can remove the [!DNL] tags here for Adobe Experience Platform and source connector. Also let's reword "sources" to just sources. The [!DNL] tag in "Zendesk Search API" can also be removed.

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +    * Go to the Zendesk [register](https://www.zendesk.com/register/) page to register and create a Zendesk account, if you do not have one already.
Since there is only one prerequisite, we can restructure this to just one short paragraph. Something like: "Before you can configure a Zendesk source connection, you must first ensure that you have Zendesk Support account. If you do not have a Zendesk Support account, go to the [Zendesk register](https://www.zendesk.com/register/) to register and create your Zendesk Support account before attempting to do this tutorial.

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +![Zendesk domain](../../../../images/tutorials/create/zendesk/zendesk-domain.png?lang=en)
We can probably just skip this domain screenshot and just add a link to "Zendesk website" in the credential tables

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +![Dataflow page](../../../../images/tutorials/create/zendesk/dataflow-monitoring.png?lang=en)
Let's add a sentence between these two screenshots, describing the step that transitions between them. Something along the lines of: "Next, select the dataflow run ID of the dataflow that you want to view, to see specific details about that dataflow run."

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +1. Next, select the **[!UICONTROL Data governance]** tab, you will see the schema details.
We can rephrase this to something like: "the **[!UICONTROL Data governance]** tab to see the schema details."

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +* A list of supported mappings that are to be set up for the [!DNL Zendesk Search API > Export Search Results](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/#export-s
Can we rephrase this to something like: "The table below outlines a list of supported mappings that must be set up for the [!DNL Zendesk Search API > Export Search Results](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/#export-search-results)."

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +exl-id:
We can remove "exl-id" here as it is auto-generated.

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +This [!DNL Adobe Experience Platform] [!DNL sources connector](https://experienceleague.adobe.com/docs/experience-platform/sources/home.html?lang=en) leverages the [!DNL Zendesk Search API > Export S
We can remove the three DNL tags in this paragraph and let's reword "sources" to just "source"

2022-05-18 04:21 UTC, carlojavier commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +![Zendesk domain](../../../../images/tutorials/create/zendesk/zendesk-domain.png?lang=en)
Like the UI doc, we can remove this domain screenshot and just add a link to "Zendesk website" in the screenshot

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +| subdomain | Unique domain specific to your account created during the registration process. <br/><br/> Refer to the [Zendesk documentation](https://support.zendesk.com/hc/en-us/articles/44093813835
It should be inform of url, https should be added to host with the subdomain.
https://support.zendesk.com/hc/en-us/articles/4409381383578-Where-can-I-find-my-Zendesk-subdomain-#:~:text=https%3A//yoursubdomain.zendesk.com

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +By following this tutorial, you have established a connection to your *Zendesk* account. You can now continue on to the next tutorial and [configure a dataflow to bring data into Platform](https://ex
@carlojavier for rest based connector preview screen input will be somewhat different. There would be no table or folder selection as it is in CRM and cloud based sources.

In rest user either needs to provide some input parameters or if input params are not there  then he will see the preview of the data.

Should be there preview screen in documentation as we have added for mailchimp campaign similar to that section defining the preview of zendesk ? - 

https://experienceleague.adobe.com/docs/experience-platform/sources/ui-tutorials/create/marketing-automation/mailchimp-campaigns.html?lang=en#:~:text=Once%20your%20source%20is%20authenticated

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "source": "results.id",
`results` should be replace with `result` as it would be single object not an array.

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "id": "2526ee57-0af4-46ea-a477-720a53108145",
connectionSpec id should be - `0a27232b-2c6e-4396-b8c6-c9fc24e37ba4`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "specName": "OAuth generic-rest-connector",
specName should be - `OAuth2 Refresh Code`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +                "host":{ZENDESK_SUBDOMAIN}
missing double quotes - `"host": "{ZENDESK_SUBDOMAIN}"`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +| `auth.params.` | Contains the credentials required to authenticate your source. |
`auth.params.` params missing.
 Please refer : https://experienceleague.adobe.com/docs/experience-platform/sources/api-tutorials/create/marketing-automation/mailchimp-campaign.html?lang=en#:~:text=authenticate%20your%20source%20to%20Platform.-,auth.params.host,-The%20root%20URL%20used%20to

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "results": {
`results` should be `result`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "links": {
links, meta should not be visible as part of preview. Could be removed from preview.

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "results": {
`results` to `result`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "id": "6360f136-5980-4111-8bdf-15d29eab3b5a",
connectionSpec id should be - `0a27232b-2c6e-4396-b8c6-c9fc24e37ba4`

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +        "mappings": [
duplicate "mappings" attributes

2022-05-24 18:02 UTC, vivetiwa commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +        "id": null,
`"id": null` could be removed

2022-05-24 19:30 UTC, carlojavier commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +By following this tutorial, you have established a connection to your *Zendesk* account. You can now continue on to the next tutorial and [configure a dataflow to bring data into Platform](https://ex
@vivetiwa good call, thanks for heads up on this. We'll definitely update this page to be similar to the mailchimp doc structure

2022-05-24 19:56 UTC, carlojavier commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "source": "results.id",
Does this apply to all values for `source` in this section or just `results.id`?

2022-05-25 04:22 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "results": {
Checked the curl response, it is results. I'll share the API request, response to you on slack.

2022-05-25 04:27 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "source": "results.id",
@vivetiwa This was the exact response from the curl request

2022-05-25 04:28 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +                "host":{ZENDESK_SUBDOMAIN}
Good spot.

2022-05-25 04:34 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +        "mappings": [
Good spot.

2022-05-25 04:37 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +| `auth.params.` | Contains the credentials required to authenticate your source. |
Thanks @vivetiwa, added.
@carlojavier the template doesn't provide guidance on this. Suggest to add guidance.

2022-05-25 04:39 UTC, mohan-h commented on help/sources/tutorials/api/create/customer-success/zendesk.md
> +            "results": {
curl response has the attribute as results.

2022-05-25 04:43 UTC, mohan-h commented on help/sources/tutorials/ui/create/customer-success/zendesk.md
> +By following this tutorial, you have established a connection to your *Zendesk* account. You can now continue on to the next tutorial and [configure a dataflow to bring data into Platform](https://ex
@carlojavier sorry didn't understand need guidance.

2022-08-08 11:14 UTC, mohan-h commented
The documentation for the connector has been made live at:
https://experienceleague.adobe.com/docs/experience-platform/sources/connectors/customer-success/zendesk.html?lang=en

2022-08-08 11:14 UTC, closed without merging